# Generated by Django 5.1.6 on 2025-02-12 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_choirmember_options_choirmember_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choirmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
