# Generated by Django 4.2.19 on 2025-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_voice_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='voice_part',
            field=models.CharField(blank=True, choices=[('S1', 'Soprano 1'), ('S2', 'Soprano 2'), ('A1', 'Alto 1'), ('A2', 'Alto 2'), ('T1', 'Tenor 1'), ('T2', 'Tenor 2'), ('B1', 'Bass 1'), ('B2', 'Bass 2')], max_length=2, null=True),
        ),
    ]
